### ISSUE TITLE
Channel on search page not showing

### ISSUE THREAD

**Issue by EnzoLiv** [lassekongo83/yt-classic-polymer#1]
When you search for an channel on the search page, the channel dont show up.
![Screenshot_19](https://user-images.githubusercontent.com/66948669/103438721-ca2dfb00-4c14-11eb-86d5-8a3852312409.png)
Can you please, fix this bug? Thanks.

**Comment by lassekongo83** [comment]
I'm unable to reproduce this. Are you using any other extension or userscript for YouTube?

**Comment by EnzoLiv** [comment]
Oh yes, was an extension called "Video Blocker". Disabled it and now works fine. Thanks for the reminder.
