### ISSUE TITLE
YouTube Click To Play

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#10]
Дополнение к этой теме - https://github.com/lassekongo83/yt-classic-polymer/issues/8

Есть ли возможность добавить в Ваше расширение добавить подобный функционал?

**YouTube Click To Play** - https://greasyfork.org/ru/scripts/406420-youtube-click-to-play

**Comment by lassekongo83** [comment]
This should be handled by the browser, either by default or by a setting. I have not encountered any videos that autoplay on new tabs unless they are focused.

**Comment by GdeZsqyAY** [comment]
> This should be handled by the browser, either by default or by a setting. I have not encountered any videos that autoplay on new tabs unless they are focused.

https://www.youtube.com/channel/UCNl5fSLbWJrVjze3PVjPnbg

Открыть любое видео

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0410/1b/_2f85b7c8e799072389ada417d009841b.jpeg)](https://fastpic.ru/view/114/2021/0410/_2f85b7c8e799072389ada417d009841b.png.html)

Видео начинает воспроизводиться

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0410/a8/_f15cafab18466a0fbcc9985c742b2fa8.jpeg)](https://fastpic.ru/view/114/2021/0410/_f15cafab18466a0fbcc9985c742b2fa8.png.html)

**Comment by lassekongo83** [comment]
New option: `"Auto-pause videos to prevent autoplay"` will be available in the next release.
