### ISSUE TITLE
YouTube: Age Verification Bypass

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#11]
Есть ли возможность добавить в Ваше расширение добавить подобный функционал?

**YouTube: Age Verification Bypass** - https://greasyfork.org/ru/scripts/375525-youtube-age-verification-bypass

**Comment by lassekongo83** [comment]
Out of scope for this extension. Just use the userscript.

**Comment by OliverSakic** [comment]
Use this website: https://tube.incognet.io/

it's basically a light version of youtube and it lets you watch Age Restricted videos.
