### ISSUE TITLE
Like bar and buttons be green and red.

### ISSUE THREAD

**Issue by positron7120** [lassekongo83/yt-classic-polymer#12]
Is it possible to make the like bar and the buttons ![image](https://user-images.githubusercontent.com/81792364/114276798-e0362d80-9a45-11eb-9ad7-6a661b400749.png) green (for likes) and red (for dislikes) and let it be like that even after pressing the like button and not be like this blue ![image](https://user-images.githubusercontent.com/81792364/114278085-a6682580-9a4b-11eb-926a-fd176d2e1f57.png).

I had seen this [style sheet](https://www.reddit.com/r/youtube/comments/hv0w5d/stylesheet_to_make_polymer_youtube_more_like_the/) with this block of code for it
```
/* Make likes/dislikes red & green, like God intended */
#container.ytd-sentiment-bar-renderer
{
	background-color: var(--paper-red-500);
}
#like-bar.ytd-sentiment-bar-renderer
{
	background-color: var(--google-green-500);
}
```
but this does not implement the last part.
Also, thank you for making this extension!

**Comment by lassekongo83** [comment]
I've decided not to spend any time on this as it's not accurate with the old design. Green and red thumbs were not available back in 2015 according to the [spritemap](https://github.com/lassekongo83/yt-classic-polymer/blob/master/src/img/spritemap.png). The thumbs were still blue and grey back then.
