### ISSUE TITLE
YouTube Sidebar appears on Every Page with Firefox

### ISSUE THREAD

**Issue by moriel5** [lassekongo83/yt-classic-polymer#15]
OS: Linux (Solus)
Browsers: Firefox Nightly (affected), Edge Dev (not affected)

Since the last update, 0.3.0, YouTube's sidebar automatically appears in Firefox, even if the screen is to narrow to warrant it.
Case in point, I am using a 19" 5:4 1280x1024p monitor as my main monitor, and can see this happen when the extension is enabled (I usually redirect to Invidious).
No such issue with Edge.

In this case, it was blank until I moved the cursor over it, however usually it shows the usual items in it, so this second issue was probably a one-time thing, however the fact that the sidebar appears every time I open a new page, is not a one-time thing.
![image](https://user-images.githubusercontent.com/20175297/114442801-7ab87d00-9bbc-11eb-8f6b-ee025c0ee714.png)

**Comment by lassekongo83** [comment]
Does it help if you disable the setting `Collapse the guide menu by default`? On Firefox you can access the settings by clicking the green puzzle icon in your address bar.

**Comment by moriel5** [comment]
I'll test it right away.

**Comment by moriel5** [comment]
It would appear that I had already set that (I already configured the extension in a previous version), so no, it does not help.

**Comment by moriel5** [comment]
Thanks, I have tested, and this issue has not returned.
