### ISSUE TITLE
Profile picture is still circle and doesn't go on banner on your own channel

### ISSUE THREAD

**Issue by Diyamund** [lassekongo83/yt-classic-polymer#16]
Hi, I was noticing if you go on your own channel with Classic Polymer, this happens.
![image](https://user-images.githubusercontent.com/44238627/114652028-b29dee00-9caa-11eb-92df-1daa666f56f2.png)
Please fix this. It only happens on your own channel.

**Comment by lassekongo83** [comment]
This is tricky for me to test, but see if the new version fixes this.

**Comment by positron7120** [comment]
The new version fixes it for me.

**Comment by positron7120** [comment]
It also fixed the issue of the profile picture overlapping with the channel name for channels without any banner image example this [channel](https://www.youtube.com/channel/UCHFMqVNbzdPTwdCnw7P_r2g/videos).
