### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#19]
<a href="https://fastpic.ru/view/114/2021/0428/_ecf116ecbb7ca0b0b2cb6f52fcc673f7.png.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0428/f7/_ecf116ecbb7ca0b0b2cb6f52fcc673f7.jpeg" border="0"></a> <a href="https://fastpic.ru/view/114/2021/0428/_610e46e31c48c01dcc08fdf9eef08998.png.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0428/98/_610e46e31c48c01dcc08fdf9eef08998.jpeg" border="0"></a>

Раньше в логотипе присутствовал красный цвет, теперь же вместо красного цвета присутствует серый. Так и должно быть?

**Comment by lassekongo83** [comment]
The old design did not have a dark theme, so no dark logotype was available in the old [image spritemap](https://github.com/lassekongo83/yt-classic-polymer/blob/master/src/img/spritemap.png)

I worked around that by adding `html[dark="true"] yt-icon.ytd-topbar-logo-renderer{filter:grayscale(1) invert(1)!important;}` to invert the text color of the logo. The downside is that the whole logo will be grey, but at least the text can be seen.

I may create a proper dark logotype in the future.

**Comment by GdeZsqyAY** [comment]
Спасибо за быстрый и развернутый ответ.
