### ISSUE TITLE
Profile picture missing on the channel page.

### ISSUE THREAD

**Issue by positron7120** [lassekongo83/yt-classic-polymer#3]
This is with the extension off.
![image](https://user-images.githubusercontent.com/81792364/113383184-faff0700-93a0-11eb-890f-d8a44dea44f2.png)

This is with the extension on and the profile picture vanishes.
![image](https://user-images.githubusercontent.com/81792364/113383080-bd01e300-93a0-11eb-9381-96d9303a44ba.png)

**Comment by lassekongo83** [comment]
Note: Avatar position will be at the classic place inside the channel banner image. (Top left.)

**Comment by positron7120** [comment]
Okay, thank you.

**Comment by positron7120** [comment]
The profile picture has now come down instead of being on the channel banner.
![image](https://user-images.githubusercontent.com/81792364/132995845-30a70105-2dae-480c-80a0-914821ea5c04.png)

**Comment by lassekongo83** [comment]
I had to move it back as I couldn't find a reliable way to keep it here after YouTube changed something.

**Comment by positron7120** [comment]
Okay.
