### ISSUE TITLE
Vit Registry Fix: Professional

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#33]
Сегодня заметил одну деталь в **yt-classic-polymer**, а именно: Вчера чистил **Windows 7 х64** от мусора вот этой программой **Vit Registry Fix: Professional** и после этих действий в  **yt-classic-polymer** были изменены настройки которых я не делал. Самостоятельно включились два пункта, которые у меня были выключены на тот момент.

Либо это случайное совпадение или же **Vit Registry Fix: Professional** может вносить изменения в настройки **yt-classic-polymer**.

**Comment by lassekongo83** [comment]
The program most likely removed the storage in your browser. That's where the settings are stored.
