### ISSUE TITLE
Автоматическое обновление

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#35]
Скажите пожалуйста, а можно сделать автоматическое обновление при нажатии на кнопку Обновление

<a href="https://fastpic.ru/view/114/2021/0617/_38da5488f4135dd152297b40d2273bd5.png.html" target="_blank"><img src="https://i114.fastpic.ru/thumb/2021/0617/d5/_38da5488f4135dd152297b40d2273bd5.jpeg" border="0"></a>

Что бы если есть новая версия, то обновление происходило бы автоматически, а не в ручном режиме как сейчас?

**Comment by lassekongo83** [comment]
It is not possible with unlisted Chromium extensions, and I have no plan of submitting this extension to the Chrome store. Only the Firefox version can be updated automatically.
