### ISSUE TITLE
the related videos show more button not work still!

### ISSUE THREAD

**Issue by MarkoczekTV** [lassekongo83/yt-classic-polymer#40]
yup

**Comment by lassekongo83** [comment]
Works for me. Are you using the latest version of the extension? And which browser version?

**Comment by randomperson189** [comment]
It only sometimes works for me, but rarely. I tried this with all extensions off.

**Comment by positron7120** [comment]
It also does not work for me with the extension version 0.4.0 and Microsoft Edge Version 93.0.933.1 (Official Build) dev (64-bit).

**Comment by MarkoczekTV** [comment]
newest version of extention and cent browser also newest version

**Comment by lassekongo83** [comment]
I can reproduce if I navigate by middle click, or by directly entering a video page from the address bar. I have no idea why.
