### ISSUE TITLE
New YouTube Update.

### ISSUE THREAD

**Issue by dietzFronder** [lassekongo83/yt-classic-polymer#41]
YouTube decided to adapt its icons from mobile devices and bring them to the web version of the site. This is what it looks like with your extension (yt-classic-polymer).
![New Icons](https://user-images.githubusercontent.com/58661662/130270370-f90ea35d-da6a-4d13-9676-1bfeeeadda31.png)

**Comment by samiscool51** [comment]
i have a youtube video open with the old icons still active, i don't know how to extract them but i did save the html data that makes up the svg icons:
[old youtube icons.txt](https://github.com/lassekongo83/yt-classic-polymer/files/7024579/old.youtube.icons.txt)
it might be incomplete but it's the best i can do

**Comment by samiscool51** [comment]
heres an updated version with two icons that i missed (the ones that appear when you hover over a video and some options appear)
[old youtube icons.txt](https://github.com/lassekongo83/yt-classic-polymer/files/7024779/old.youtube.icons.txt)

**Comment by samiscool51** [comment]
i keep missing more, this one contains icons inside the transcript and report menu's (the radio button is the same but lighter for some reason)
[old youtube icons.txt](https://github.com/lassekongo83/yt-classic-polymer/files/7024933/old.youtube.icons.txt)
that should be all of them but considering this is version 3, i might be missing more... tag me if you find anymore and i'll add it.

**Comment by lassekongo83** [comment]
I've added a new option that should restore the icons. It's experimental still, so not everything may be restored. You may have to `ctrl+f5` the page (to clear the cache) when enabling the option.
