### ISSUE TITLE
White space showing up on the top in full screen mode.

### ISSUE THREAD

**Issue by positron7120** [lassekongo83/yt-classic-polymer#42]
Something in YouTube has made a white space persistent on the top of the video, which pushes the video down and hides the controls and bottom portion of the video.
![image](https://user-images.githubusercontent.com/81792364/131161987-1442f15f-fe00-430c-8466-e8982533f0ce.png)

I had to downgrade to version 0.3.3 which, fixed the issue.

**Comment by positron7120** [comment]
I tried it even in InPrivate mode without any additional extensions it still shows up.
I am currently on Microsoft Edge Version 94.0.992.1 (Official Build) dev (64-bit).

**Comment by lassekongo83** [comment]
Do you have the setting `Display the old horizontal navigation bar` enabled?

What happens if you right click the empty space and select inspect? Does it have a css class or anything?

**Comment by positron7120** [comment]
Yes, I have the ```Display the old horizontal navigation bar``` option enabled but, even after disabling it, the issue persists.
Also, sometimes this happens.
![image](https://user-images.githubusercontent.com/81792364/131213738-cd595e31-9597-4a93-82f5-7d7ad505da17.png)
The title bar stays there even on full screen.

When I try to see what the white bar is, using developer tools it highlights the whole screen with this element.
![image](https://user-images.githubusercontent.com/81792364/131214002-5b86b5f0-9777-4473-8206-2b5f192e346b.png)

And this element shows up when I click through.
```<ytd-app scrollbar-color style="--ytd-app-fullerscreen-scrollbar-width:17px; --ytd-masthead-height:56px;">…</ytd-app>```

**Comment by lassekongo83** [comment]
I do not think the new release will fix this issue (except for the fullscreen header). I'm just guessing.

It may be some new style introduced by some YouTube A/B-test on your end, which I'm not in yet.

**Comment by positron7120** [comment]
The problem has been fixed now.
Thank You.
