### ISSUE TITLE
Add the ability to disable scrolling on full screen.

### ISSUE THREAD

**Issue by positron7120** [lassekongo83/yt-classic-polymer#5]
I would love it if it was possible to remove the scrolling on full-screen which YouTube has added with the polymer layout.

**Comment by positron7120** [comment]
The option to disable scrolling on fullscreen no longer works.

**Comment by lassekongo83** [comment]
I can reproduce if I navigate by middle click, or by directly entering a video page from the address bar. I have no idea why.
