### ISSUE TITLE
Дизлайки

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#51]
https://www.youtube.com/ - убрал возможность ставить дизлайки. Но умельцы смогли вернуть их - https://chrome.google.com/webstore/detail/return-youtube-dislike/gebbhagfogifgggkldgodflihgfeippi

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/58640411/151654307-04d62ca7-68d8-412d-8b54-c281f073fc81.png)

</details><br/>

Просто не хочется нагружать браузер дополнительными расширениями. Может есть возможность это реализовать в Вашем расширении?

Было бы просто отлично если удастся это реализовать.

**Comment by lassekongo83** [comment]
Too much work to implement a feature like this, and probably beyond my skill level.

**Comment by GdeZsqyAY** [comment]
> Too much work to implement a feature like this, and probably beyond my skill level.

Спасибо за честный ответ.
