### ISSUE TITLE
Задний фон

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#6]
Привет!

Белый фон конечно привычный, но в ночное время с белым фоном глазам не очень комфортно.

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0404/6f/_0ac5fd8114932f34dec3a64bbd47336f.jpeg)](https://fastpic.ru/view/114/2021/0404/_0ac5fd8114932f34dec3a64bbd47336f.png.html)

Можно сделать еще и темный фон?

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0404/96/_87cb56ef6265d8ecc92cb2ddaea07796.jpeg)](https://fastpic.ru/view/114/2021/0404/_87cb56ef6265d8ecc92cb2ddaea07796.png.html)

Ну или дать пользователю самому решать какой фон будет - белый или черный.

**Comment by positron7120** [comment]
YouTube has the option to switch between dark and light theme if signed in, otherwise, it follows the theme used by the browser. Is it this or something else?

**Comment by GdeZsqyAY** [comment]
> YouTube has the option to switch between dark and light theme if signed in, otherwise, it follows the theme used by the browser. Is it this or something else?

А без входа в систему можно как то переключать со светлой на темную?

**Comment by positron7120** [comment]
> > YouTube has the option to switch between dark and light theme if signed in, otherwise, it follows the theme used by the browser. Is it this or something else?
> 
> And without logging in, you can somehow switch from light to dark?

Yes, by switching the theme of the browser as I have said in my previous comment.

**Comment by positron7120** [comment]
> > YouTube has the option to switch between dark and light theme if signed in, otherwise, it follows the theme used by the browser. Is it this or something else?
> 
> А без входа в систему можно как то переключать со светлой на темную?

I just realised the YouTube theme can be changed without changing the browser theme by clicking on these buttons as specified in the screen shots attached below.
![image](https://user-images.githubusercontent.com/81792364/113515488-6a881880-9592-11eb-8c3b-e0ec8f42d435.png)
then whichever of the three options you want
![image](https://user-images.githubusercontent.com/81792364/113515507-8f7c8b80-9592-11eb-95ba-7daac92d8067.png)

**Comment by GdeZsqyAY** [comment]
Спасибо!
