### ISSUE TITLE
Боковая панель

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#7]
Сейчас боковая панель отключена

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0404/6f/_0ac5fd8114932f34dec3a64bbd47336f.jpeg)](https://fastpic.ru/view/114/2021/0404/_0ac5fd8114932f34dec3a64bbd47336f.png.html)

Но раньше она была постоянно включена

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0404/7a/_0d3736657dfb34cbc63fba13aff3167a.jpeg)](https://fastpic.ru/view/114/2021/0404/_0d3736657dfb34cbc63fba13aff3167a.png.html)

Можно сделать как и раньше, а именно с постоянной включенной боковой панелью?

**Comment by positron7120** [comment]
If I understand you correctly, you want the sidebar permanently on, and for that, there is a setting in the extension options called 'collapse side menu by default' which can be unchecked for the sidebar to be permanently there.

**Comment by GdeZsqyAY** [comment]
> If I understand you correctly, you want the sidebar permanently on, and for that, there is a setting in the extension options called 'collapse side menu by default' which can be unchecked for the sidebar to be permanently there.

Покажите пожалуйста где этот пункт находится и что с ним нужно сделать, что бы боковая панель всегда была включена?

**Comment by positron7120** [comment]
> > If I understand you correctly, you want the sidebar permanently on, and for that, there is a setting in the extension options called 'collapse side menu by default' which can be unchecked for the sidebar to be permanently there.
> 
> Please show where this item is and what should be done with it, that the sidebar was always turned on?

You can access the extension options by clicking on the extension in the extension bar and then options (as underlined in red).
![image](https://user-images.githubusercontent.com/81792364/113511348-06a72500-957d-11eb-8a18-64ecf1aab5a6.png)

**Comment by GdeZsqyAY** [comment]
**positron7120** - спасибо Вам за помощь, вопрос закрыт.

**Comment by positron7120** [comment]
@GdeZsqyAY your welcome.
