### ISSUE TITLE
Автозапуск видео

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#8]
Можно ли добавить также скрипт, который будет блокировать автозапуск видео на главной страницы и на выбранном видеофайле?

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0404/1e/_c7e478e8947182b46fde81ff7415411e.jpeg)](https://fastpic.ru/view/114/2021/0404/_c7e478e8947182b46fde81ff7415411e.png.html)

**Comment by lassekongo83** [comment]
This will be a new option in the next release.
