### ISSUE TITLE
gstatic.com

### ISSUE THREAD

**Issue by GdeZsqyAY** [lassekongo83/yt-classic-polymer#9]
Какое отношение имеет - **gstatic.com** к **YouTube**?

[![FastPic.Ru](https://i114.fastpic.ru/thumb/2021/0406/e7/77a86b0bbf04fdfba1fd3f61971e3de7.jpeg)](https://fastpic.ru/view/114/2021/0406/77a86b0bbf04fdfba1fd3f61971e3de7.png.html)

Сделайте активным возможность выбора давать доступ или нет.

**lassekongo83** - огромное Вам **СПАСИБО** за отличное расширение.

**Comment by lassekongo83** [comment]
https://github.com/lassekongo83/yt-classic-polymer/blob/e1b06b74a558ebc7d5520c28263ef7df0a610708/src/js/background.js#L8

It's to block promo images.
